### ISSUE TITLE
Receipt for credits payback

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_shopping_cart#108]
We need a possibility to show credits that were paid back in the shopping cart receipt.

- [x] Add new placeholder(s)
- [x] Implement logic for placeholder(s)
- [x] Adjust receipt-template HTML so we can show the credits that were paid back

**Comment by bernhard-wunderbyte** [comment]
@georgmaisser When you have time, please have a look at my proposed solution in branch GH108-receipt-for-credits-payback
