### ISSUE TITLE
MUSI-633 Den Warenkorb für eine Person befüllen und befüllt lassen.

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_shopping_cart#114]
Es ist bereits möglich, als Kassier den Warenkorb einer Person zu befüllen. Es sollte auch möglich sein, dass der Warenkorb für diese Befüllung nicht gelöscht wird.

**Comment by georgmaisser** [comment]
- [ ] Im Zuge dieses Tickets: Bei checkout (test auf open orders table) wird die expiration time mal fünf (setting) genommen.
