### ISSUE TITLE
DB scheme inconsistencies in shopping cart

### ISSUE THREAD

**Issue by bernhard-wunderbyte** [Wunderbyte-GmbH/moodle-local_shopping_cart#18]
**php admin/cli/check_database_schema.php** revealed inconsistencies:
```
local_shopping_cart_history
 * column 'identifier' has incorrect type 'C', expected 'I'
 * column 'canceluntil' has default '0', expected 'NULL' (I)
-------------------------------------------------------------------------------
local_shopping_cart_ledger
 * column 'tax' size is (10,2), expected (10,3) (N)
```

**Comment by Frankhe78** [comment]
This inconsistency might have come from different branches. I forked from the main branch into a new branch def-frh.

On a different subject, the database column 'main' can actually become 'not null', at the moment it is still null.

**Comment by dasistwas** [comment]
It would b great if you could fix that in db/upgrade.php

**Comment by bernhard-wunderbyte** [comment]
@dasistwas Can we close this issue already?

**Comment by dasistwas** [comment]
I think we can close that.
