### ISSUE TITLE
Misleading interactions in checkoutp process

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_shopping_cart#50]
In the checkout process, the user is misleaded in 3 ways. That is really confusing for users, even for me. This process occurs when I have a sub-booking added to a normal booking.

First I click on "Add to cart" button (That is OK)

![Screenshot 2023-08-29 at 11-58-10 Halbjahreskarte](https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/assets/1620975/706ec7ea-881a-4cce-af3b-7708ea880198)

Then I get to this dialogue as a modal:

![Screenshot 2023-08-29 at 11-51-02 Halbjahreskarte](https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/assets/1620975/10422ac4-e5ab-46da-ac31-eac656045d7a)

There are 3 UX problems on this interaction:

1) A questions is asked and there is no option provided how I could answer to this question. I would expect a button like "Yes I want to book" or similar thing. When such a question is asked, then the interaction has to reply to this question

2) I have 2 choices: Either click on "Add to cart" or "Continue". BUT: I just clicked add to cart button, why should I click it again? I would expect a confirmation page but not agein "Add to cart", an action I already performed

3) There is a continue button. It is not clear what the continue button is for. Is the item added when I click on the continue button without clicking on the "Add to cart button" again?

A single button with "Confirm adding X to cart and continue to the next step" would be enough. Or something like: 

You selected XY, in order to proceed with the checkout click "Continue". But do not ask "Do you want to book XY?" (I would expect a YES/NO) option with that question.

**Comment by bernhard-wunderbyte** [comment]
Fixed in Booking 8.0.37
