### ISSUE TITLE
When item is deleted, the amount transferred to payment provider is not updated

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_shopping_cart#51]
How to reproduse: See video.

[Screencast from 2023-08-29 12-17-18.webm](https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/assets/1620975/c589c31e-0751-444f-bd7d-e8977aa2ea37)

Expected behavior:
Pass correct amount to payment provider when item is deleted from shopping cart in 
/local/shopping_cart/checkout.php

**Comment by bernhard-wunderbyte** [comment]
Fixed in f2327789d083a8e045c7e2594dd307facbf25f5c.
