### ISSUE TITLE
Test for cashout (positive and negative)

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_shopping_cart#54]

**Comment by semteacher** [comment]
Could you please explain how this feature could be accessed and how it works?

**Comment by bernhard-wunderbyte** [comment]
You also find this on the cashier page:
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/assets/78346453/2e20eccc-0835-427d-8361-8e40f8e989cc)

This feature is used when cash is paid (or paid back) at the cashier's desk so the sums will show a correct cash balance. So what you'll need to check is only, if the entries in cash report are made.

**Comment by semteacher** [comment]
2 behat tests has been created
https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/commit/2fbd2880ecaebfd5b8360c01230e3f03f1df2f31
