### ISSUE TITLE
Test for cash transfer (from one cashier to another)

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_shopping_cart#55]

**Comment by semteacher** [comment]
Could you please explain how this feature could be accessed and how it works?

**Comment by bernhard-wunderbyte** [comment]
You find it on the cashier page:
![Image](https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/assets/78346453/531ce01d-2ebd-421b-ba78-1f9103e17ba6)

![Image](https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/assets/78346453/4a9a6e8b-c1fd-4fa9-8041-95e086a3c2f8)

It's actually very simple. Cash is moved from one cashier to another. This means that entries in cash report (local_shopping_cart_ledger) are made:

The cash is removed from the first cashier and added to the second cashier:

![Image](https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/assets/78346453/700f4efa-d4f1-4eef-98de-3318e78a361d)

**Comment by bernhard-wunderbyte** [comment]
Please note that you only can select users with the "local/shopping_cart:cashier" capability.
