### ISSUE TITLE
Tests for credits manager

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_shopping_cart#56]

**Comment by semteacher** [comment]
What exact featires have to be covered with tests? I found
- correct credit balance (add / reduce) - working OK for manual test
- payback - allow to refund any emount 
Does something else available?

**Comment by bernhard-wunderbyte** [comment]
When using payback, you have to check the cash report (table: local_shopping_cart_ledger). Payback means, that not only the credit is changed but also the cashier balance is changed. This means that the value is also stored in "price":



![Image](https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/assets/78346453/ea8624c9-6148-471c-9034-669c5c1873cd)

**Comment by bernhard-wunderbyte** [comment]
Additional info:

Currently there are only three options:
(1) correct credits (if there have been errors)
(2) pay back credits with cash
(3) pay back credits with bank transfer

Also there are extra buttons to pay back the full credit with cash or bank transfer.

**Comment by semteacher** [comment]
Implemented via
https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/commit/674ed3d3afaa12f01bdb782a4bbd2bd670b2bc1c
https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/commit/c02115705e9cc576d2dce4dbbe5b8034b2757013
https://github.com/Wunderbyte-GmbH/moodle-local_shopping_cart/commit/13f6e4cbfb514e449a1b285343b1052b904afb35
