### ISSUE TITLE
"Kein Preis für Preiskategorie Preis vorhanden"

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-local_shopping_cart#87]
Moodle 4.1, neueste dafür verfügbare Versionen von Warenkorb und Booking

Ich habe nur die Preiskategorie "Preis" aktiv, in der Buchungsoption ist ein Preis eingetragen. Dennoch bekomme ich die Meldung "Kein Preis für Preiskategorie Preis vorhanden" und kann den Kurs nicht buchen. 

![image](https://github.com/user-attachments/assets/192381d6-ac42-49ce-a06f-650aff82875e)
![image](https://github.com/user-attachments/assets/f9eac3e5-b9aa-41ca-b317-d3d19cd9043a)

**Comment by georgmaisser** [comment]
Hallo, das funktioniert ein wenig anders. Die erste Preiskategorie hat immer den identifier "default". Im ausgewählten custom user profile filed muss daher "default" stehen. In ihrem Beispiel hat der user den Wert "Preis" in dem Feld stehen.

Wenn eigene identifier verwendet werden sollen, kann man einfach eine weitere Kategorie erstellen, die dann auch den identifier "Preis" haben kann.

In den letzten development Versionen gibt es ein Setting, um im Fall einer nicht gefundenen Preiskategorie immer auf default zurückzufallen, siehe Bild:


![Bildschirmfoto 2024-10-01 um 13 30 06](https://github.com/user-attachments/assets/41bdfbf7-57f3-4553-accd-503889f1caf4)

**Comment by VOOM108** [comment]
Wie kommt denn die Kategorie initial in das Profilfeld der User? Jetzt haben scheinbar alle User da "Preis" stehen. Wenn ich jetzt die erste Kategorie default nenne, und eine 2. mit Preis anlege und dafür einen Wert einstelle, dann würden erstmal alle bestehenden User erfasst und könnten Buchen? Aber was ist mit neuen Usern, bekommen die dann initial "default" in ihr Profilfeld?

**Comment by VOOM108** [comment]
Ich habe jetzt die DEV von Warenkorb und Booking installiert, sodass ich jetzt weiterkomme. Die Antwort auf die Frage würde mich aber dennoch interessieren. :)

**Comment by georgmaisser** [comment]
Die Profilfelder sind Standard Moodle Funktionalitäten. Wenn als Default Wert "Preis" angegeben ist, dann werden alle Nutzerinnen auch "Preis" drinnen stehen haben.

Wenn Sie die Werte nicht ändern wollen wird es am leichtesten sein, eine zweite Preiskategorie mit dem Identifier "Preis" anzulegen.

Ich hoffe Sie verstehen, dass wir hier zu konkreten Einstellungen und Settings (vor allem wenn sie Funktionen von Core Moodle betreffen) keinen Support geben können. Wir bemühen uns die Doku zu erweitern und aktuell zu halten, siehe dazu auch showroom.wunderbyte.at .

Ansonsten können wir gerne ein Support-Paket anbieten und Ihnen helfen, Ihre Plattform zu konfigurieren.
