### ISSUE TITLE
Tests failing for PHP 7.4 Versions

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-local_shopping_cart#90]
Actions are repeatedly failing for the lowest moodle / php versions. 
It seems as if there was a connection problem. 
Running tests locally in this environment seems alright.
Is this maybe a configuation issue? 
Is there anything we can do about it?

**Comment by semteacher** [comment]
reason for the failure is the trailing comma in the method definition
![image](https://github.com/user-attachments/assets/a7fe9a59-f714-4763-8fc3-e0e2447b05e8)
We should use trailing comma only in multi-line arrays.

**Comment by eynimeni** [comment]
great, thank you!
