### ISSUE TITLE
Musi - Show Merchantref instead of tid, if saved in open orders table

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-local_shopping_cart#91]

**Comment by bernhard-wunderbyte** [comment]
Achtung: Setting `local_shopping_cart | cashreportshowcustomorderid` muss aktiv sein, damit die merchantref angezeigt wird. Ansonsten wird nicht auf die tid aus der openorders-Tabelle zugegriffen, sondern auf die xx_orderid aus der Tabelle des Payment-Plugins.
